url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "kyteidev" # the name of your site, e.g. ACME Corp.
postcss:
  cache: false

sass:
  load_paths:
    - _sass
    - node_modules

include: ["node_modules/tailwindcss"]
