on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install

      - name: Install Jekyll and Dependencies
        run: |
          gem install bundler
          bundle install
          npm install

      - name: Build the Site
        run: bundle exec jekyll build --future

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: _site/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
